export class CastingsService{
    headers=["ID","Name","System_Name","Title","Description","Start_Date","End_Date"];
    CastingList=[
        {
            ID:1,
            Name:'Betty',
            System_Name:'Actrice',
            Title:'Carte',
            Description:'Bonjour',
            Start_Date:'29/45/4894',
            End_Date:'20/45/789'
        },
        {
            ID:1,
            Name:'Betty',
            System_Name:'Actrice',
            Title:'Carte',
            Description:'Bonjour',
            Start_Date:'29/45/4894',
            End_Date:'20/45/789'
        },
        {
            ID:1,
            Name:'Betty',
            System_Name:'Actrice',
            Title:'Carte',
            Description:'Bonjour',
            Start_Date:'29/45/4894',
            End_Date:'20/45/789'
        },
        {
            ID:1,
            Name:'Betty',
            System_Name:'Actrice',
            Title:'Carte',
            Description:'Bonjour',
            Start_Date:'29/45/4894',
            End_Date:'20/45/789'
        }
    ];
    function1(){
        console.log("Bonjour tout le monde");
    }
}