export class CreateService{
    languages=["FR","EN"];
    Users=[
        {
            Culture:"FR",
            email:'betty_bla.yopmail',
            password:'123456',
            roles:["Administrator","E-shop-Manager"],
            culture:["fr-LU","fr-FR","fr-BE"]
        },
        {
            Culture:"EN",
            email:'redda_bla.yopmail',
            password:'123456',
            roles:["CMS_Viewver"],
            culture:["en-IE","en-GB","en-US"]
        },
        {
            Culture:"EN",
            email:'pedro_bla.yopmail',
            password:'123456',
            roles:["Content_Manager","E-shop-Manager"],
            culture:["en-IE","en-GB"]
        },
        {
            Culture:"FR",
            email:'lucie_bla.yopmail',
            password:'123456',
            roles:["Administrator","E-shop-Manager"],
            culture:["fr-LU","fr-FR","fr-BE"]
        }
    ];
}